name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0, v2.1.3, etc.

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for creating releases and uploading assets
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      
    - name: Extract version from tag
      id: get_version
      run: |
        # Remove 'v' prefix from tag to get version number
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"
        
    - name: Update version in build.gradle
      run: |
        # Update the version in build.gradle to match the tag
        sed -i "s/version='.*'/version='${{ steps.get_version.outputs.version }}'/" build.gradle
        echo "Updated build.gradle version to ${{ steps.get_version.outputs.version }}"
        
    - name: Build with Gradle
      run: ./gradlew clean build
      
    - name: Run tests
      run: ./gradlew test
      
    - name: Verify JAR was built
      run: |
        if [ ! -f build/libs/*.jar ]; then
          echo "Error: No JAR file found in build/libs/"
          exit 1
        fi
        echo "JAR build verification passed"
      
    - name: Get JAR filename
      id: jar_name
      run: |
        # Find the built JAR file
        JAR_FILE=$(find build/libs -name "*.jar" -not -name "*-sources.jar" -not -name "*-javadoc.jar" | head -1)
        JAR_BASENAME=$(basename "$JAR_FILE")
        # Create a release-specific JAR name
        RELEASE_JAR_NAME="systemverilog-importer-${{ steps.get_version.outputs.version }}.jar"
        echo "jar_file=$JAR_FILE" >> $GITHUB_OUTPUT
        echo "jar_basename=$JAR_BASENAME" >> $GITHUB_OUTPUT
        echo "release_jar_name=$RELEASE_JAR_NAME" >> $GITHUB_OUTPUT
        echo "Found JAR: $JAR_FILE"
        echo "Release JAR name: $RELEASE_JAR_NAME"
        
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Create release with JAR asset using GitHub CLI
        gh release create ${{ github.ref_name }} \
          --title "Release ${{ github.ref_name }}" \
          --notes "## SystemVerilog Importer ${{ github.ref_name }}
          
        ### Changes
        - Automated release for version ${{ steps.get_version.outputs.version }}
        
        ### Downloads
        - **JAR file**: \`${{ steps.jar_name.outputs.release_jar_name }}\`
        
        ### Installation
        1. Download the JAR file from the assets below
        2. Use it with OpenFastTrace as an importer plugin
        
        ### Requirements
        - Java 17 or higher
        - OpenFastTrace 4.1.0 or higher" \
          ${{ steps.jar_name.outputs.jar_file }}#${{ steps.jar_name.outputs.release_jar_name }}